<?php

/**
 * Implements hook_form_alter().
 */
function islandora_marcxml_datastream_retainer_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'islandora_marcxml_file_form') {
    $form['next']['#submit'] = array_merge(array('islandora_marcxml_retainer_form_submit'), $form['next']['#submit']);
  }
}

/**
 * XML Form submission.
 */
function islandora_marcxml_retainer_form_submit($form, &$form_state) {
  module_load_include('inc', 'islandora_marcxml', 'includes/utilities');
  $file = file_load($form_state['values']['file']);
  if ($file) {
    $object = islandora_ingest_form_get_object($form_state);
    if (empty($object['MARCXML'])) {
      $ds = $object->constructDatastream('MARCXML', 'M');
      $ds->label = 'MARCXML Record';
      $object->ingestDatastream($ds);
      $created = TRUE;
    }
    else {
      $ds = $object['MARCXML'];
    }
    $ds->content = file_get_contents($file->uri);
  }
}
